#! /bin/sh
#
# Etud		startup script for the Ethernet over UDP daemon
#
#		Written by Daniel Lawson <daniel@meta.net.nz>
#
# Version:	$Id: Etud,v 1.8 2003/02/13 12:12:44 mattgbrown Exp $
#
ETUDCONF=/usr/local/etc/etud.conf
DAEMON=/usr/local/sbin/Etud
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
ARGS="-f $ETUDCONF -p $PIDFILE"
NAME=Etud
DESC="EtherneT over Udp Daemon"
IP=/bin/ip

# Check for the Etud configuration file
if [ ! -f ${ETUDCONF} ]; then
        echo Could not find etud configuration file
        exit
fi

# Parameter defaults
IFNAME=wan0
CTRLFILE=/var/run/Etud.ctrl
PIDFILE=/var/run/Etud.pid
# Retrieve the real values from the config file if they exist
while read parameter value
do
	if [ "$parameter" == "pidfile" ]; then
                PIDFILE=`echo "$value" | tr -d '"'`
        elif [ "$parameter" == "ctrlfile" ]; then
		CTRLFILE=`echo "$value" | tr -d '"'`
	elif [ "$parameter" == "ifname" ]; then
		IFNAME=`echo "$value" | tr -d '"'`
	fi
done < $ETUDCONF

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	[ -e $CTRLFILE ] && {
        	echo Control file exists, Etud already running?
		exit 1;
	}


	echo  "Starting $DESC: $NAME"
	start-stop-daemon --start --quiet --exec $DAEMON -- $ARGS
	
	ifup ${IFNAME}
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME "
	ifdown ${IFNAME}
	start-stop-daemon --stop --quiet --pidfile $PIDFILE  \
		--exec $DAEMON -- $ARGS
	echo "."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo -n "Reloading $DESC configuration..."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	$PIDFILE --exec $DAEMON -- $ARGS
	# echo "done."
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#

	echo -n "Restarting $DESC: $NAME"
	ifdown ${IFNAME}
	start-stop-daemon --stop --quiet --pidfile \
		$PIDFILE --exec $DAEMON -- $ARGS
	sleep 1
	start-stop-daemon --start --quiet --exec $DAEMON -- $ARGS
	ifup ${IFNAME}
	echo "."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
