#! /bin/sh
#
# wand		startup script for wand
#
#		Written by Daniel Lawson <daniel@meta.net.nz>
#
# Version:	$Id: wand,v 1.4 2002/12/02 11:12:08 cuchulain Exp $
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/sbin/wand
NAME=wand
DESC="Wide Area Network Daemon"
WAND_CONF=/usr/local/etc/wand.conf
PID_FILE=/var/run/$NAME.pid

ARGS=" -f ${WAND_CONF} -p ${PID_FILE} "
if [ ! -f ${WAND_CONF} ]; then
        echo Could not find configuration file ${WAND_CONF}
        exit
fi

test -x $DAEMON || exit 0

set -e
case "$1" in
  start)
	echo "Starting $DESC: $NAME "
	start-stop-daemon --start --quiet --pidfile ${PID_FILE} \
			--exec $DAEMON -- $ARGS
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME "
	start-stop-daemon --stop --quiet --pidfile ${PID_FILE} \
		--exec $DAEMON
	echo "."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo -n "Reloading $DESC configuration..."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid --exec $DAEMON
	# echo "done."
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: $NAME "
	start-stop-daemon --stop --quiet --pidfile \
		$PIDFILE --exec $DAEMON
		--exec $ETUD
	sleep 1
	start-stop-daemon --start --quiet --pidfile ${PID_FILE} \
			--exec $DAEMON -- $ARGS
	echo "."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
